s = "CTGGGCTGGTGCCTACGCGCTAAAGGATCGCTCGTAATACTTTAGAGAATACGGAAGCGGAGTCCCAATGGTTCAGGCGATTCAACTCCTAGACCCCAGGGTATTCT" \
    "TGATGACAGACAGTCCTTCCTACCCTGAAACGTGGCCTAGGTCTACCCGACAAAAAACCCATATGTAACATCTCCGCATGACTACTATATCGGGATCGGATGTGTA" \
    "ATGGAAGAAGTCTGCGTCGTGTATCAGTTCTTGTAGTGCTTCCTTTCAGGCCATTCTTATCTACAATACTGACGTTTGGGCGTCTCCATTAAGCCGGTCTTTTGGA" \
    "AGGCTGCGAGGTAGCTCTAACGCCCCAGGATTTGTAGAAGGTAAGTGATTGTATAAAAAGAGTTATGGGGTTCCAGTCTTACGCGGTGTTCGCGGATTTGGGTTCAT" \
    "TACGTTAATATTACCTTATGGTCCGAAATCATAAAATCAATGAAAACGAAAAAGGAGTTACTACCTGCCTCAGATAGCTACAGCGGCCAGAATGAAACCACTCC" \
    "TTCGGAAGTAAAGATAATGCGCATCGCTCGCGCGCCAATCCTCGGTACATAAAAGCCACTTCAAAGACGTATCTCTAGTGAGAATCCGATCTGCAGATTCTACCTA" \
    "GCGCCGGGAATCAATCCCTGAAAGCTAACGTGAAATTGAATGGTGAAAAGATGCCAGTGGACTCTCAATCCCAGGTATAATTCACTAAGTGTAACAATTGCGAG" \
    "GGTTTCATAAGGTGAAAGTGATAAGAAGAATCGTTTGAATCGAACGATGGTACGAATCGTTCCACTGTCTCGAAGGGCAACCGATACGTGCCGTTGTATCGCT" \
    "CCACAGAGACAGCGGTACTTATAGTATAGATGGCGCATCAGGGCGTATCTTTTTGTGGTCCGCCGCCTTCTCGCTATAATTCTACAGAAACTTACCCTTGTCAGTGAT"
t = "CGACGCACCAGCAAATCGCGGAAACCAGCGCTTGCAAGATGAGAGTTAATGCACATGCGAAGTTCTATCTGTACAGTGAATCGAGTTCCTGCGACACCATGGAT" \
    "ACAGCTTGAATGAAACCTGTCGTTTGCGTCAGAATTGCCCAAAAGTTCCCCGTAAAATCAACGTTGTTCTCCTCTGCCCGATGACTTCTAGATACGCCTCCGATA" \
    "TGGATTGCAAAACGTTTGGCTCATGCGGTGGCCTTGGTTCGGCGCGCTTTTCCCTCGTGCATATAGAGATTTCTGGCATGTGACACTGACGATTCTGTCGACCTT" \
    "ACGGATTGCTACTTAGTATTTCTCGATCCAGAGAACTTAGTGAAGCCAATTGATAGCATAACAAGAGGAAAACGAGTGATGTGTTCCCAGGTGGAGTCGGATATA" \
    "TAACCATTAGGATAATACACCCTACTAGTCCGAAATTTTAATATCCCTGTCAACGAAGAATGGATCACCGAACACCGCAGGGATCAAGAGACCCGCGCCTGTA" \
    "TCAACCCACAGAAAAGTCTATACTTAGAGCACTACAAGATCACCACTACTCAATTCCTTGAAGGAAGTTGAACGACGTATCTCCAGTTATATTCCTGTCTACA" \
    "GTGCGCGGCGCGCACGTGGATGTAAGACCAAAGAGGTAACATCTTGTTATACAATGATCACTCTCCACTCTTCCCGAAATCCCTATGAACACTATTACGATGT" \
    "TACTAGGCTATTGGAATTATAGCGAGAATTTAATCACGAGACTGTGTCGTATCGATCAATGCGTAGCCGTCCTACTAGCACTCGATGGGCCCCGGATGTGTC" \
    "TTTTTTCAACGCAATACGGACATCGGGAGAGTTGTTCGACTGAACGTGGGTTTTGCGCACACTGGTTGAGAAACTACGCAGCAGCGTTTGGATTCGGTAGGAT" \
    "ATTATACTTGTCTGTGTC"
x = 0
count = 0
for letters in range(0, len(s)):
    if s[x] != t[x]:
        count += 1
    x += 1

print(count)
